---
- name: Install k3s
  hosts: all 
  gather_facts: false
  
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 60
  
    - name: Gather facts
      setup:

    - name: Update package list
      yum:
        update_cache: yes

    - name: Upgrade packages
      become: true
      yum:
        name: "*"
        state: latest

    - name: Download k3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install-k3s
        mode: 0755
  
    - name: Install k3s
      shell: /tmp/install-k3s
      environment:
        K3S_KUBECONFIG_MODE: "644"
      register: result
  
    - name: Print k3s install result
      debug:
        var: result.stdout_lines

- name: Deploy service
  hosts: all

  tasks:
  - name: Copy files
    copy:
      src: manifests.yaml
      dest: /tmp/manifests.yaml
      mode: 0644
  - name: Apply manifests
    command:
      cmd: kubectl apply -f /tmp/manifests.yaml