apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: "ghcr.io/zhdkirill/eleveo:main"
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: counter
spec:
  type: LoadBalancer
  selector:
    app: counter
  ports:
  - port: 8080
    targetPort: 5000