- name: Install k3s
  become: true
  block:
  - name: Download k3s install script
    get_url:
      url: https://get.k3s.io
      dest: /tmp/install-k3s
      mode: 0755
  - name: Install k3s
    shell: /tmp/install-k3s
    environment:
      K3S_KUBECONFIG_MODE: "644"
    register: result
  always:
  - name: Print k3s install result
    debug:
      var: result.stdout_lines