name: Deployment

on:
  push:
    branches:
      - main
      - ci

jobs:
  deploy:
    name: AWS
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: true
      
      - name: 'Init terraform'
        run: terraform init
      
      - name: 'Plan terraform'
        id: plan
        run: terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Deploy'
        id: deploy
        run: terraform apply -auto-approve -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Test'
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ steps.deploy.outputs.instance_ip }}:8080/
          max-attempts: 30
          retry-delay: 10s

      - name: 'Cleanup'
        id: cleanup
        if: ${{ always() }}
        run: terraform destroy -auto-approve -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
